version: '2'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    expose:
      - 8069
    command: odoo 
    volumes:
      - odoo_data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - '5432:5432'

    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  odoo_data:
  postgresql_data:
networks:
  default:
    external:
      name: odoo_one_default

