version: '2'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    expose:
      - 8069
    command: odoo -d odoo_14_ee
    volumes:
      - odoo_data14:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo-db-socket:/var/run/postgresql # For Odoo 8.0 only
      - ./extra_addons:/opt/extra_addons
      - ../enterprise:/opt/enterprise
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - '5432:5432'

    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - odoo-db-socket:/var/run/postgresql # For Odoo 8.0 only
      
volumes:
  odoo_data14:
  postgresql_data:
  odoo-db-socket:  # For Odoo 8 only
networks:
  default:
    external:
      name: odoo_one_default

