# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addon_title_table_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddonTitle(object):
    def setupUi(self, AddonTitle):
        AddonTitle.setObjectName("AddonTitle")
        AddonTitle.resize(126, 29)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddonTitle)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_addon_display_name = QtWidgets.QLabel(AddonTitle)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_addon_display_name.setFont(font)
        self.label_addon_display_name.setObjectName("label_addon_display_name")
        self.verticalLayout.addWidget(self.label_addon_display_name)
        self.label_addon_name = QtWidgets.QLabel(AddonTitle)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_addon_name.setFont(font)
        self.label_addon_name.setObjectName("label_addon_name")
        self.verticalLayout.addWidget(self.label_addon_name)

        self.retranslateUi(AddonTitle)
        QtCore.QMetaObject.connectSlotsByName(AddonTitle)

    def retranslateUi(self, AddonTitle):
        _translate = QtCore.QCoreApplication.translate
        AddonTitle.setWindowTitle(_translate("AddonTitle", "Form"))
        self.label_addon_display_name.setText(_translate("AddonTitle", "Addon Display Name"))
        self.label_addon_name.setText(_translate("AddonTitle", "technical_name"))
