# This workflow will install Python dependencies, and generate Odoo addons files.

name: Update Odoo Addons List

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-addons-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate JSON files
        run: |
          python github_modules.py ${{ secrets.GITHUB_TOKEN }} -v 16.0 -r web
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Odoo Addons List
          file_pattern: 'github_modules_*.json'
